In [1]:
import numpy as np
import time 
from math import inf

In [21]:
board = np.zeros((3,3),dtype = np.int)
HUMAN = -1
COMP  = +1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [22]:
board

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [46]:
def main():
  h_choice = "O"
  c_choice = "X"

  while( (len(empty_locations(board)) > 0)  and not game_over(board)):
    ai_turn(c_choice,h_choice)
    human_turn(c_choice,h_choice)

  if(wins(board,HUMAN)):
    print('HUMAN TURN')
    print(board)
    print('\nYOU WIN!\n')

  elif(wins(board,COMP)):
    print('COMPUTER TURN')
    print(board)
    print('\YOU LOSE!\n')
  
  else:
    print(board)
    print('\nDRAW\n')
  


In [50]:
def wins(state,player):
  win_states = [
                 state[0, :].tolist(), # 1st row  
                 state[1, :].tolist(), # 2st row 
                 state[2, :].tolist(), # 3st row 
                 state[:, 0].tolist(), # 1st col 
                 state[:, 1].tolist(), # 2st col 
                 state[:, 2].tolist(), # 3st col 
                 [state[0, 0], state[1, 1], state[2, 2]], # 1st diagonal
                 [state[2, 0], state[1, 1], state[0, 2]]] # 2st diagonal
     
  if[player,player,player] in win_states:
    return True
  else:
    return False

In [33]:
def game_over(state):
  return wins(state,HUMAN) or wins(state,COMP)

In [34]:
def empty_locations(state):
  l =[]
  for i in range(3):
    for j in range(3):
      if(state[i][j] == 0):
        loc =(i,j)
        l.append(loc)
  return l

In [54]:
def valid_move(x,y):
  if(board[x,y] == 0):
    return True

In [55]:
def set_move(x,y,player):
  if(valid_move(x,y) == True):
    board[x,y] = player
    return True
  else:
    return False

In [37]:
def evaluate(state):
  if(wins(state,COMP)):
    score = +1
  elif(wins(state,HUMAN)):
    score = -1
  else:
    score =0

  return score

In [38]:
def minimax(state,depth,player):
  if(player == COMP):
    best = [-1,-1,-inf]
  
  else:
    best = [1,1,inf]
  
  if(depth == 0 or game_over(state)):
    score = evaluate(state)
    return [-1,-1,score]
  
  for i in empty_locations(state):
    (x,y) = i
    state[x,y] = player
    score = minimax(state,depth-1,player)
    state[x,y] = 0
    score = [x,y,score[2]]

    if(player == COMP):
      if(score[2] > best[2]):
        best = score
    else:
        if(score[2] < best[2]):
          best = score
  
  return best


In [39]:
string = """
| 1 | 2 | 3 |
| 4 | 5 | 6 |
| 7 | 8 | 9 |
"""

In [52]:
def ai_turn(c_choice,h_choice):
  depth = len(empty_locations(board))

  if(depth == 0 or game_over(board)):
    return
  
  print('COMPUTER TURN ')
  print(board)

  if(depth == 9):
    x = np.random.choice([0,1,2])
    y = np.random.choice([0,1,2])
  else:
    move = minimax(board,depth,COMP)
    (x,y) = move[0],move[1]
  
  set_move(x,y,COMP)
  time.sleep(1)

In [41]:
def human_turn(c_choice,h_choice):

  moves = {1:[0,0],
           2:[0,1],
           3:[0,2],
           4:[1,0],
           5:[1,1],
           6:[1,2],
           7:[2,0],
           8:[2,1],
           9:[2,2],
           }
  move = -1
  depth = len(empty_locations(board))
  if(depth == 0 or game_over(board)):
    return
  
  print(board)
  print(string)

  while(move < 1 or move > 9):
    try:
      move = int(input("Use Keypad (only 1 to 9\n"))
      coord = moves [move]
      try_move = set_move(coord[0],coord[1],HUMAN)

      if(try_move == False):
        print('Bad Move')
        move = -1
    
    except:
      print('Bad Move')
            

In [56]:
main()

COMPUTER TURN 
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 1]
 [0 0 0]
 [0 0 0]]

| 1 | 2 | 3 |
| 4 | 5 | 6 |
| 7 | 8 | 9 |

Use Keypad (only 1 to 9
2
COMPUTER TURN 
[[ 0 -1  1]
 [ 0  0  0]
 [ 0  0  0]]
[[ 1 -1  1]
 [ 0  0  0]
 [ 0  0  0]]

| 1 | 2 | 3 |
| 4 | 5 | 6 |
| 7 | 8 | 9 |

Use Keypad (only 1 to 9
5
COMPUTER TURN 
[[ 1 -1  1]
 [ 0 -1  0]
 [ 0  0  0]]
[[ 1 -1  1]
 [ 1 -1  0]
 [ 0  0  0]]

| 1 | 2 | 3 |
| 4 | 5 | 6 |
| 7 | 8 | 9 |

Use Keypad (only 1 to 9
7
COMPUTER TURN 
[[ 1 -1  1]
 [ 1 -1  0]
 [-1  0  0]]
[[ 1 -1  1]
 [ 1 -1  1]
 [-1  0  0]]

| 1 | 2 | 3 |
| 4 | 5 | 6 |
| 7 | 8 | 9 |

Use Keypad (only 1 to 9
9
COMPUTER TURN 
[[ 1 -1  1]
 [ 1 -1  1]
 [-1  0 -1]]
[[ 1 -1  1]
 [ 1 -1  1]
 [-1  1 -1]]

DRAW

